changelog:
  exclude:
    labels:
      - 'ignore-for-release'
    authors:
      # Ignore the release PR created by github-actions
      - 'github-actions'
  categories:
    - title: 'ğŸ’¥ Breaking Changes'
      labels:
        - 'change: breaking'
    - title: 'âœ¨ Features'
      labels:
        - 'change: feat'
    - title: 'ğŸš€ Performance'
      labels:
        - 'change: perf'
    - title: 'ğŸ› Bug Fixes'
      labels:
        - 'change: fix'
    - title: 'ğŸ“– Documentation'
      labels:
        - 'change: docs'
    - title: Other Changes
      labels:
        - '*'
